from __future__ import annotations

from typing import Protocol


class Storage(Protocol):
    async def incr(self, key: str, ttl_sec: int) -> int: ...

    async def set(self, key: str, value: str, ttl_sec: int) -> None: ...

    async def get(self, key: str) -> str | None: ...

    async def delete(self, key: str) -> None: ...

    async def sadd(self, key: str, value: str, ttl_sec: int) -> int: ...

    async def scard(self, key: str) -> int: ...

    async def lpush_trim(self, key: str, value: str, max_len: int, ttl_sec: int) -> None: ...

    async def lrange(self, key: str, start: int, end: int) -> list[str]: ...
